language: node_js
node_js:
  - "8"

if: branch = master

script: npm run build

cache:
  directories:
    - intermediate
    - node_modules
    - $HOME/.npm

before_deploy:
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file:
    - "release/gas_pipelines.geojson.gz"
    - "release/liquid_pipelines.geojson.gz"
    - "release/all_pipelines.ndjson.gz"
    skip_cleanup: true
    on:
      branch: master
